### ISSUE TITLE
Fabric 1.18.1 - Added Kambrik & Bountiful - Instant Crash on Startup

### ISSUE THREAD

**Issue by xR4YM0ND** [ejektaflex/KambrikDocs#3]
Hey there, 

i got lots of mods in my pack on Curseforge App 
when i added Kambrik & Bountiful i got an instant crash
when i remove both, the game starts up at least

[crash-2022-01-07_15.51.16-server.txt](https://github.com/ejektaflex/KambrikDocs/files/7829477/crash-2022-01-07_15.51.16-server.txt)
[crash-2022-01-07_15.51.18-client.txt](https://github.com/ejektaflex/KambrikDocs/files/7829478/crash-2022-01-07_15.51.18-client.txt)
[latest.log](https://github.com/ejektaflex/KambrikDocs/files/7829480/latest.log)

**Comment by ejektaflex** [comment]
Ah, I'll release a fix for this. For now, go back a version of Kambrik to 3.0.0.
